experiment:
  exp_dir: experiments/
  exp_name: conll03
  seed: 42

task: named-entity-recognition

dataset:
  data_dir: https://data.deepai.org/conll2003.zip
  data_type: sequence_labeling
  data_format: column

preprocessor:
  type: sequence-labeling-preprocessor
  model_dir: xlm-roberta-large
  max_length: 100

data_collator: SequenceLabelingDataCollatorWithPadding

model:
  type: sequence-labeling-model
  encoder:
    model_name_or_path: xlm-roberta-large
  word_dropout: 0.1
  use_crf: true

trainer: ner-trainer

train:
  max_epochs: 20
  dataloader:
    batch_size_per_gpu: 16
  optimizer:
    type: AdamW
    lr: 5.0e-6
    param_groups:
      - regex: crf
        lr: 5.0e-2
  lr_scheduler:
    type: LinearLR
    start_factor: 1.0
    end_factor: 0.0
    total_iters: 20

evaluation:
  dataloader:
    batch_size_per_gpu: 128
  metrics:
    - type: ner-metric
    - type: ner-dumper
      model_type: sequence_labeling
      dump_format: column
