experiment:
  exp_dir: experiments/
  exp_name: ud1

task: part-of-speech

dataset:
  name_or_path: ud1_pos
  namespace: izhx404

preprocessor:
  type: sequence-labeling-preprocessor
  model_dir: bert-base
  max_length: 256
  bio2bioes: true

data_collator: SequenceLabelingDataCollatorWithPadding

model:
  type: sequence-labeling-model
  encoder:
    model_name_or_path: babert-base
  word_dropout: 0.1
  use_crf: true

trainer: ner-trainer

train:
  max_epochs: 30
  dataloader:
    batch_size_per_gpu: 32
    workers_per_gpu: 1
  optimizer:
    type: AdamW
    lr: 2.0e-5
  lr_scheduler:
    type: LinearLR
    start_factor: 1.0
    end_factor: 0.0
    total_iters: 30

evaluation:
  dataloader:
    batch_size_per_gpu: 128
    workers_per_gpu: 1
    shuffle: false
  metrics:
    - type: ner-metric
    - type: ner-dumper
      model_type: sequence_labeling
      dump_format: column
